package transcode

// Drift test for the generated loss matrix: the checked-in LOSS_MATRIX.md
// must byte-match the document regenerated from the registry, every
// registered key must be documented, and every documented key must be
// registered — code and documentation cannot drift (review-z commit 2).

import (
	"os"
	"strings"
	"testing"
)

// TestLossMatrixDrift proves LOSS_MATRIX.md is generated from the registry.
func TestLossMatrixDrift(t *testing.T) {
	matrix, err := os.ReadFile("LOSS_MATRIX.md")
	if err != nil {
		t.Fatal(err)
	}
	// Reconstruct the generated document the same way the generator does:
	// the drift test must not depend on running go generate.
	var b strings.Builder
	b.WriteString("# Loss matrix\n\n")
	b.WriteString("Generated from the granular loss-key registry in `losses.go` by `go generate` —\n")
	b.WriteString("see losses.go. Do not edit this file by hand; the drift test in\n")
	b.WriteString("loss_matrix_drift_test.go proves it never drifts from the registry.\n\n")
	b.WriteString("Every non-portable feature is gated by exactly one granular, direction-specific\n")
	b.WriteString("loss key. The default strict policy rejects every loss; a mapping approves\n")
	b.WriteString("individual keys via `-transcode-allow-loss`.\n\n")
	b.WriteString("| Loss key | Loss description |\n")
	b.WriteString("| --- | --- |\n")
	for _, key := range RegisteredLossKeys() {
		b.WriteString("| `" + string(key) + "` | " + LossKeyDescription(key) + " |\n")
	}
	b.WriteString("\n")
	if string(matrix) != b.String() {
		t.Fatal("LOSS_MATRIX.md is not generated from the loss registry; run `go generate ./internal/transcode`")
	}
}

// TestLossMatrixRegistryComplete proves every registered key is documented
// and every documented key is registered (the matrix is complete in both
// directions).
func TestLossMatrixRegistryComplete(t *testing.T) {
	matrix, err := os.ReadFile("LOSS_MATRIX.md")
	if err != nil {
		t.Fatal(err)
	}
	text := string(matrix)
	for _, key := range RegisteredLossKeys() {
		if !strings.Contains(text, "`"+string(key)+"`") {
			t.Fatalf("registered key %q is not documented in LOSS_MATRIX.md", key)
		}
		if LossKeyDescription(key) == "" {
			t.Fatalf("registered key %q has no description", key)
		}
	}
	// Every matrix row names a registered key.
	for _, line := range strings.Split(text, "\n") {
		if !strings.HasPrefix(line, "| `") {
			continue
		}
		name := strings.TrimPrefix(line, "| `")
		name = name[:strings.Index(name, "`")]
		if _, ok := allLossKeys()[Feature(name)]; !ok {
			t.Fatalf("matrix documents unregistered key %q", name)
		}
	}
}
